### ISSUE TITLE
Привести страничку подробного описания в порядок

### ISSUE THREAD

**Issue by Alexey-Myshevskiy** [Alexey-Myshevskiy/taskBoard#10]
Сейчас на странице подробного описания пустые поля. Разобраться и поправить.
![2016-12-07 16-16-56](https://cloud.githubusercontent.com/assets/8824833/20971132/fca24fa6-bc98-11e6-9edb-30ae257dc348.png)

**Comment by Evgeniy-Kovtun** [comment]
№10 Закрыто. Отображение меню зарегистрированого пользователя в описании задачи
