### ISSUE TITLE
Дубликаты в выпадающем списке

### ISSUE THREAD

**Issue by Alexey-Myshevskiy** [Alexey-Myshevskiy/taskBoard#12]
Если добавить пользователя в проект, потом выйти и зайти под тем пользователем, в выпадающем списке "участники проекта" дублируются емейлы.
![2016-12-09 15-10-43](https://cloud.githubusercontent.com/assets/8824833/21050309/98b90c10-be22-11e6-93c4-d14d047336c3.png)

**Comment by Dmytro-Opria** [comment]
b6fd360 Исправлен баг с дубликатом е-мейлов в выпадающем списке
