### ISSUE TITLE
Форматированый вывод в коротком описании задачи

### ISSUE THREAD

**Issue by Alexey-Myshevskiy** [Alexey-Myshevskiy/taskBoard#13]
На таскбоарде в карточке задачи выводятся теги вместо форматирования текста описания самой задачи.
![_001](https://cloud.githubusercontent.com/assets/8824833/21050359/e7718062-be22-11e6-87a5-16d9d37ce87f.png)
![_011](https://cloud.githubusercontent.com/assets/8824833/21050360/e773b472-be22-11e6-8b7f-672af3c0773f.png)

**Comment by Evgeniy-Kovtun** [comment]
№13 Закрыто. 12122016
